version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
      - ./editor_files:/app/editor_files
    environment:
      - ENV=production
      - MAX_WORKERS=4
      - CORS_ORIGINS=https://yourdomain.com
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3