name: Deploy

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["Test"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Production GCP VM
      env:
        PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.GCP_VM_HOST }}
        USERNAME: ${{ secrets.GCP_VM_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        mkdir -p ~/.ssh
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        
        # Deploy ONLY to prod environment
        ssh -i private_key $USERNAME@$HOST "cd /opt/prod/collaborative-ai-editor && \
          git pull origin master && \
          docker-compose -f docker-compose.prod.yml down && \
          docker-compose -f docker-compose.prod.yml up -d --build"
