name: Test

on:
  push:
    branches: [ test, master ]
  pull_request:
    branches: [ test, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install -e .
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/ -v

    - name: Create Pull Request to master
      # Only create PR if we're on test branch and tests passed
      if: success() && github.ref == 'refs/heads/test'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_GITHUB }}
        commit-message: 'Automated PR from test to master'
        branch: test-to-master
        delete-branch: true
        title: 'Merge test into master'
        body: 'All tests have passed. Ready to merge into master.'
        base: 'master'
        head: 'test'

