name: Test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install -e .
    
    - name: Run tests
      run: |
        pytest
        
    - name: Create Pull Request to master
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/test'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_GITHUB }}  # Using PAT instead of GITHUB_TOKEN
        commit-message: 'Automated PR from test to master'
        branch: test-to-master
        delete-branch: true
        title: 'Merge test into master'
        body: 'All tests have passed. Ready to merge into master.'
        base: 'master'
        head: 'test'

